In [1]:
import torch
import torch.utils.data as data_utils
import torch.nn as nn
import torch.optim as optim
import torchvision.models as models
import tqdm
import time
import copy
from torch.optim import lr_scheduler
from torchvision import datasets
from sklearn.metrics import roc_curve

max_epochs=3

# CUDA for PyTorch
use_cuda = torch.cuda.is_available()
device = torch.device("cuda:0" if use_cuda else "cpu")

In [4]:
model = models.vgg19(pretrained=False)

for param in model.parameters():
    param.requires_grad = False
    
in_features = model.classifier[-1].in_features

model.classifier[6] = nn.Linear(in_features, 2)                   

criterion = nn.CrossEntropyLoss(weight=torch.Tensor([1,5]).to(device))
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
exp_lr_scheduler = lr_scheduler.StepLR(optimizer, step_size=7, gamma=0.1)

model = model.cuda()

In [16]:
malign_count = 0
for chunk in range(10):
    Y = torch.load('data/labels-' + str(chunk) + '.pt')
    print(Y.sum())
    malign_count += Y.sum()
1 - 2286/21639

tensor(228)
tensor(216)
tensor(229)
tensor(236)
tensor(239)
tensor(225)
tensor(244)
tensor(226)
tensor(226)
tensor(217)


0.8943574102315264

In [8]:
train_model(model, criterion, optimizer, exp_lr_scheduler, num_epochs=10, chunks=9)

Epoch 1/10
----------
train Loss: 101.7711 Acc: 0.4917
val Loss: 11.8745 Acc: 0.7980
Epoch 2/10
----------
train Loss: 81.2141 Acc: 0.5205
val Loss: 14.6899 Acc: 0.8307
Epoch 3/10
----------
tensor([ 21.7659,  67.3232,  31.6996, 154.5877,  31.2627, 152.3798,  84.2595,
        187.6634, 126.5163, 123.3075,  44.4879,  31.0935,  -4.6674,  92.8584,
         45.8597,  67.7417,  98.6124, 162.7464, 119.4016,   4.4486,  32.2928,
          3.4130,  33.8120,  88.9051, 168.2034,  32.9952, 215.4153,  55.4850,
        109.3170,  14.2181, 211.2370, 145.8534,  64.9913, 140.6700,   0.4803,
         37.2375,  49.2092,  37.9319,  73.5203,  74.4357, 157.9990,   1.4631,
         18.6665,  86.8316, 128.5952,  70.7716,  93.1061,   8.1524,  66.7859,
         63.6580,  11.7171,  69.9743, 176.9747,  35.4362,  96.1671, 178.6960,
         72.8020, 184.3669, 144.9571,  12.7641,  63.4026,  22.5484,  83.8251,
         20.5920], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 

tensor([138.8690,  88.0592,   5.3088,  78.6778, 185.5705,  19.1102,  51.5677,
         32.4819,  74.0085, 232.1406,  -2.0014,  62.5720, 113.0206,  87.7438,
        102.7514, 130.8787, 102.2491,  43.6750, 139.1896, 168.9995,  62.7660,
         95.5045, 207.3048, 307.1244,  24.8291,  11.1231,  54.6141,  35.9299,
         34.4741,  85.9331, 176.4812,  10.9283,  16.8201, 151.4515,  91.8220,
        104.0250,  51.8913,  99.6804,  19.4991,  71.7598,   7.1361,   4.4602,
         78.2253, 258.3453,  61.1125,  23.3094,  10.0633,  63.8445,  57.0463,
         47.0489,   9.1632, 148.5978, 162.1703, 256.9247,  43.1474,  13.9384,
        160.9823, 136.8916,  81.4113, 146.1993, 148.6964, 119.8320, 122.5605,
        124.2807], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
        0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0], device='cuda:0')
tens

tensor([ 64.9603, 118.9478,  81.2990,  69.8727,  79.8198,  73.6535, 140.7253,
         89.9593,  94.0508,   6.1331, 191.3885, 170.0962, 147.2737,  88.5879,
          9.6175,  59.6864,  40.2850,  19.5916, 200.4661, 159.5413,  23.9716,
         56.4343,   7.1105, 154.7922,  69.8426,   7.5645,  50.7371, 223.6132,
         44.2085, 138.6529, 154.2694, 115.5238,  13.9973,  82.6985,  80.3973,
        101.7344,  10.4172,  37.5453,  57.7581,  57.5570,  35.5392,  37.9458,
         -0.5707,  86.7672,  55.9209,  99.8850, 142.2278,  68.1004, 104.7295,
        103.2901,  70.1913,  39.3659,  29.9837, 265.6473, 220.7770, 191.3312,
         93.2081,   7.5445, 182.9876,  37.0767,  92.6267,  78.6896,   2.1822,
        120.7408], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
        0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0], device='cuda:0')
tens

tensor([ 2.5239e+02,  1.9736e+02,  9.3261e+01,  9.2832e+01,  2.1701e+01,
         1.0925e+02,  4.4678e+01,  6.5951e+01,  9.2942e+01,  1.8834e+01,
         4.7479e+01,  1.6687e+02,  2.1870e+01,  9.3619e+01,  2.4110e+02,
         3.0015e+01,  1.7099e+02,  1.5358e+02,  2.1836e+02,  2.2045e+01,
         6.9627e+01,  4.4264e+01,  4.5123e+01,  6.4666e+01,  2.8267e+01,
         9.2330e+01,  1.1367e+02,  8.1579e+01,  5.3143e-02,  8.9557e+00,
         1.6787e+01,  5.3476e+01,  1.7080e+01,  1.4823e+02,  1.5794e+01,
         1.7169e+02,  1.1818e+02,  1.6461e+02,  2.9268e+01,  1.1645e+01,
         2.6790e+01,  7.3786e+01,  1.6184e+02,  6.9920e+01,  2.3911e+01,
         8.8144e+01,  9.3798e+01,  1.6240e+02,  4.4967e+01,  5.6550e+01,
         3.7613e+01, -2.4267e+00,  1.3699e+02,  2.4425e+01,  4.9086e+01,
         3.5311e+00,  1.1007e+02,  1.1787e+02,  2.0697e+02,  1.8106e+02,
         1.8731e+01,  4.4720e+01,  3.9023e+01,  1.6248e+02], device='cuda:0',
       grad_fn=<MaxBackward0>) tensor([1, 1, 1

tensor([ 67.3707,  43.7089, 112.4564,  39.3785, 186.3220, 190.3651,  65.2361,
         47.7097, 134.7629,  23.2277,  47.3535, 108.0532,  77.3974, 138.9057,
        209.4430, 165.5025,  17.9218,  -2.1813, 171.6750,  13.4030, 252.7088,
         78.9673,  14.0927, 118.0632,  65.9212,  29.3210,  30.6451,  78.5137,
         72.5763,  19.3669,  87.2036,  95.0379,  71.3021,  16.9306, 117.0201,
         53.8774,  27.3234, 132.1047, 152.5656, 163.8958,  40.0834, 265.6021,
         61.1969, 170.5714,  42.0102,  25.8975,  66.1372,   9.0398, 123.8287,
         27.5949,  48.8872, 204.4662, 162.6047,  48.7485,  73.4630,  35.4048,
         61.1690,  78.9100, 156.2849, 138.5040, 201.0883, 221.3802, 248.3111,
        135.3007], device='cuda:0', grad_fn=<MaxBackward0>) tensor([0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
        1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0], device='cuda:0')
tens

tensor([ 2.7009e+02,  5.7676e+01,  3.2642e+01,  9.5788e+01,  3.4231e+01,
         3.1864e+01,  1.9733e+01,  2.8202e+01,  7.4437e+01,  1.9369e+01,
         5.5061e+01,  7.3937e+01,  4.7798e+01,  1.7282e+02,  1.0563e+02,
         1.5069e+01,  1.9098e+02,  1.6850e+01,  6.8441e+01,  1.5100e+02,
         2.5139e+01,  4.8366e+01, -1.5027e-01, -9.3182e+00,  1.3726e+02,
         9.8649e+01,  7.0379e+01,  1.0918e+02,  4.9973e+01, -3.3673e-01,
         7.8394e+01,  1.9424e+02,  5.5081e+01,  1.6903e+02,  1.5768e+02,
         1.2053e+02,  1.3835e+02,  5.8157e+01,  3.7287e+01,  3.9559e+01,
         7.1662e+00,  6.1756e+01,  3.5651e+01,  9.2678e+01,  9.8626e+01,
         3.8480e+01,  7.1344e+01,  1.4035e+02,  8.8345e+01,  3.1296e+01,
         9.9204e+01,  1.3892e+02,  6.0763e+00,  9.9063e+01,  1.7945e+02,
         1.6496e+02,  3.1187e+01,  1.5724e+02,  1.2405e+02,  1.1401e+02,
         2.2911e-01,  1.6673e+02,  8.9694e+01,  1.8574e+01], device='cuda:0',
       grad_fn=<MaxBackward0>) tensor([1, 1, 0

tensor([ 6.6219e+01,  2.7483e+02,  9.7299e+01,  3.7932e+01,  4.2064e+01,
         1.1538e+02,  5.4523e+01,  3.8198e+00,  8.9062e+00,  1.2737e+02,
         1.0950e+02,  1.6149e+02,  1.3572e+02,  1.6245e+01,  1.4957e+02,
         2.0393e+01,  2.2200e+01,  7.6324e+01,  2.5674e+02,  1.8946e+02,
         8.6022e+01,  7.5041e+01,  7.4115e+01,  4.7460e+01,  8.7759e+01,
         1.2927e+02,  1.6705e+01,  4.4978e+01,  3.6394e+01,  2.1404e+02,
         3.3647e+01,  2.7659e+01,  1.3936e+02,  1.9984e+02,  4.3313e+01,
        -7.6672e-02,  1.3801e+02,  2.7179e+01,  7.0633e+01,  7.2643e+00,
         2.2874e+02,  7.5292e+00,  9.4607e+01,  2.4440e+01,  4.0990e+01,
         6.3130e+01,  1.8794e+02,  2.0651e+02,  2.8833e+02,  4.2767e+01,
         3.4478e+01,  3.1564e+01,  1.0713e+02,  5.0847e+01,  9.7894e+01,
         3.1498e+01,  1.4606e+02,  4.2456e+01,  1.5662e+02,  7.0328e+01,
         8.8390e+01,  7.9749e+01,  6.6502e+01,  2.7954e+01], device='cuda:0',
       grad_fn=<MaxBackward0>) tensor([1, 0, 1

tensor([ 42.8107,  83.5994,  -1.4219, 277.9814, 134.8599, 196.0434, 199.7056,
        125.2654, 273.2662, 158.1430,  91.8113,  54.3803,  88.6740,  76.0731,
         36.5158,  93.9167,  44.8018, 157.7542, 171.4943,  64.9541,  64.3315,
         27.0546, 110.5648,  18.8550,  84.0289,  97.1500,   4.7340,  14.3759,
         67.5082,  66.8623, 106.1986,   9.9932,  53.9019,  36.4547, 201.3734,
          9.5302, 129.3144, 113.2542,  19.7204,  42.1825, 130.0423, 100.7519,
        139.9388,  16.9172,  39.9744, 186.2980, 164.2189,  13.7573,  41.5155,
        157.4553,  92.8567, 162.9222, 132.5011,  38.4867, 191.3474,  68.8355,
        111.4706,  56.3323, 148.4560, 128.4393, 153.0643,  36.4515,  38.3299,
         82.8028], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1], device='cuda:0')
tens

tensor([190.1000, 140.5716,  84.6269,  98.7636,  55.1393,  14.7710, 168.4281,
        343.0065,   1.2971,  25.1845,  35.2798,  49.5044,  41.4097, 337.1096,
        318.4452,   6.1105, 110.9278, 169.3823,   4.0119, 113.1379, 148.4967,
         96.5192,  26.1803,  52.2075, 225.4488,  97.6814,  58.7494, 123.7911,
         11.5688,  33.5334,  12.4336,  74.0290, 123.0796,  26.3766,  64.0576,
         56.1224,  98.9286,  17.7890,  43.8592,  70.8378,  17.6201, 208.6545,
        150.1902,   2.8459, 155.7905,  29.0326,  89.5972,  83.7312,  88.7089,
         78.7001,  10.7026,  47.1487,  23.6132,  27.0142, 205.0150, 124.4275,
         27.8419, 110.6232,  97.4104,  25.7952,  48.1704,   7.4348,  78.8319,
         52.3431], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0], device='cuda:0')
tens

tensor([ 52.1328,  54.5931,  64.7322,   8.8591,  59.5341, 105.8930,  83.4285,
         67.7110,  32.2245, 173.6246,  66.0763, 118.5850, 318.1279,  83.3936,
         96.8252,  90.4945, 147.7792, 136.1000,   3.2560,  14.8264, 165.9526,
         20.4837, 127.7250,  93.5177, 154.8451, 169.8288,  92.6334,  18.0408,
        110.5782,  26.3416, 112.6007,  86.3621, 117.9588,  31.2540,  49.0195,
         11.2243,  61.8148,  36.3394, 174.7301, 126.0287,  21.6247,  10.2035,
          3.6668,  45.0121,  21.4165, 129.5501,  24.5921, 189.3316,  36.9347,
        217.8611,  51.9179, 249.3940,  16.4415,  69.0436,   5.1677, 189.5968,
          6.4386,  78.3774,  63.9070,  86.4955,  74.9637, 123.1925,  45.0546,
         64.0092], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0], device='cuda:0')
tens

tensor([ 25.5368,  94.0160,  33.4364,  30.7118,  37.3440,  55.1012, 106.1831,
        206.8346,  35.3009, 232.9766, 151.6048,  30.5716,  18.4538,  94.6189,
        116.9044,  10.6915, 137.6774, 231.7811,  48.0565,  70.9981, 166.3617,
         14.1326, 140.7078,   6.5217,  41.1506,   0.5114,  89.0876,   7.3056,
         20.3832,  32.9319,  47.2532, 117.6258,  89.7488,  16.9287,  60.4467,
         66.8573,  71.7930,  20.4335, 147.6654, 185.4121,  57.3516,  65.9788,
         15.2346, 162.5329,  36.4174, 185.2514, 107.5753, 173.6881,  16.7059,
        234.5111,  30.4281, 205.2426, 122.1543,   8.5869,   8.7080,   0.5476,
         42.0584,  85.6216, 126.5454,  85.2102, 160.7036,  76.0450,  54.8187,
         86.9460], device='cuda:0', grad_fn=<MaxBackward0>) tensor([0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
        1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
        1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0], device='cuda:0')
tens

tensor([101.7445, 146.7351,  52.1414, 110.7997,  37.2834, 120.5658, 111.5893,
          4.8493, 171.7192, 112.9906,  78.8149,   3.1299,  50.0165, 151.5027,
         65.3637,  27.4753, 236.1002, 137.0551,  38.5601, 198.1763,   2.6318,
        139.8814,  36.3674,  95.2554, 133.9217,  23.1829,  73.9801, 128.5235,
        171.0636,  37.9245,  57.3027,  20.1485,   7.2892,   8.4315,  76.1262,
         16.8298, 212.9130,  70.7425,  44.0742, 108.0346,  43.8141,  75.9304,
         78.3272, 152.3232,  50.4665,  85.3004,  77.8423,  18.6533, 117.6665,
         22.6191,  60.9332, 218.8587, 107.6983,  76.8471,  64.4847,  33.4196,
         35.3638,  22.1166,  53.9263,  87.7110, 104.6660, 135.9377,  26.7119,
         18.6400], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1], device='cuda:0')
tens

tensor([ 3.3067e+01,  2.4009e+02,  1.2269e+02,  1.2894e+02,  7.0170e+01,
         1.9900e+02,  8.3221e+01,  3.1121e+01,  5.4083e+01,  8.0451e+00,
         1.1074e+02,  4.9583e+01,  3.6899e+01, -9.8605e-02,  6.8413e+01,
         4.5771e+01,  6.2051e+01,  6.0732e+01,  1.7009e+02,  2.2056e+02,
         1.2971e+02,  1.7624e+01,  1.4626e+02,  2.6037e+02,  6.5826e+01,
         5.8231e+01,  9.5945e+01,  4.4192e+00,  2.7848e+01,  3.6480e+01,
         3.3037e+01,  1.0608e+02,  8.9094e+01,  7.2051e+01,  8.9539e+01,
         1.4647e+02,  2.2033e+01,  1.1006e+02,  1.9012e+01,  4.1435e+01,
         1.3560e+02,  6.3507e+01,  2.0035e+02,  4.3069e+01,  5.3029e+01,
         8.7565e+01,  3.5893e+01,  3.8875e+01,  4.5390e+01,  4.5580e+01,
         4.4411e+01,  7.8271e+01,  3.5321e+01,  9.6607e+01,  1.6924e+02,
         3.6162e+01,  2.2161e+02,  1.0189e+02,  7.8020e+01,  1.7592e+01,
         8.3962e+01,  2.9424e+01,  1.2474e+02,  1.0776e+02], device='cuda:0',
       grad_fn=<MaxBackward0>) tensor([1, 1, 0

tensor([  2.9342,  27.5814, 162.9843,  99.9589,  65.0143,  58.1256,  50.8929,
        153.3779,  31.6232,  17.3984,  25.2540,  79.8775,  68.3710, 115.4779,
         74.2648, 151.4981,  24.0243,  29.3668, 139.5885,  38.2474, 217.0603,
        123.4847, 276.1530,  94.2192,  78.7157, 271.1011,  51.5350, 124.4801,
         30.2987,  46.2688,  67.3664,  51.4716,  94.3560,  71.1165,  12.3870,
        117.7086,  95.8928,  55.7641,   6.2718, 129.6123,  36.0431,  38.0061,
         26.4568, 166.1485, 133.5162,  14.1008,  65.4529,  46.3854,  15.7067,
         60.6985, 123.2302,  41.9196,  11.4221,  34.3840, 174.0886,  63.3160,
        102.7765,  47.6020, 227.3331,  65.8676,  63.1543, 186.0933,  97.3287,
         34.5594], device='cuda:0', grad_fn=<MaxBackward0>) tensor([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
        0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1], device='cuda:0')
tens

tensor([ 62.1813,  89.3583,  50.3508,  21.9650,  84.7058, 144.5715,  46.5400,
         65.8719, 105.7304, 145.5587,  64.3578,  35.3082,  21.7037,  71.0885,
         99.2088,  24.2086, 162.8825,  49.1759,  67.5718,  79.4522,  43.7419,
         77.2751,  45.5347,  78.6908, 108.4479,  18.6677, 145.0577,   0.9047,
         82.3252,  37.6209,  23.8085,  96.0911,   1.0978, 119.7215,  71.8348,
         67.3601, 202.5498,  59.2316, 119.0696, 153.0950, 296.3535,  78.2181,
          9.9578,  66.0886,  40.3469,  62.7945, 122.7923,  24.6410,  30.0063,
         28.3015,  88.4911,  70.9346,  27.1616,  35.2144,  70.8074,  45.9620,
         16.6001,  96.1426,  58.1100,  54.6051,  73.3904,  58.3060,  84.3038,
         20.1168], device='cuda:0', grad_fn=<MaxBackward0>) tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1], device='cuda:0')
tens

tensor([233.1033, 109.1894,  91.3156, 164.3344, 193.8828,  26.5385,  34.2039,
         77.6629, 132.0705, 120.2580,  78.5045, 129.6156, 190.9356, 164.1079,
         62.3551, 135.8527,  20.7712,  69.9245, 122.0990,  59.1501,  33.6443,
         22.6397,  97.9138,  52.9099, 127.0876,   5.2966,  78.3440,  99.4987,
        102.4493,  70.7432,  52.7618, 101.0156,  79.0826,   8.1463,  42.2915,
        155.3116,  59.3383, 214.8685, 116.3684, 128.4528, 100.9567,  21.8073,
         95.0549,   3.1509, 117.7255, 213.7962,  69.9986,   7.4471,  93.4233,
        104.4754,  78.3913, 129.4750,  73.1998,  11.9793, 308.5480, 305.8971,
         53.9214,  84.6734,  47.3919, 180.5870,  54.6168,   0.8281,  25.9643,
        103.3072], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
        0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1], device='cuda:0')
tens

tensor([ 10.1941, 158.1771,  42.2706,  20.9060, 152.5626,   2.9263,  49.1746,
         83.0810, 123.8500,   5.8649,  75.6164,  37.9945,  86.8677,  46.8072,
         19.4644,  24.7214,   4.7446, 161.6662, 129.8647, 106.3891,   5.7367,
         82.1367,   5.7149, 164.6843,  11.7043,  93.1954,  29.3396, 127.0564,
        127.1179,  41.3443, 141.5518, 119.5257,  41.1815,  64.0990, 176.2675,
        181.1163, 127.5997,  25.9960,   7.7234,  -7.2667,  13.5188,  34.1843,
         51.4606,  89.2255,  66.8620,  49.7881, 184.9051,  59.4556, 126.4287,
         69.5603,  14.0375,  42.9225,  35.5305,  42.7032,  43.9510,  63.9711,
         60.0152,  68.0527, 109.1704,  92.2937,  77.3190, 127.3646,  35.9719,
        156.2817], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0], device='cuda:0')
tens

tensor([178.3618,  -1.8764,  63.3670,  62.6615,   2.0037,  85.8610, 112.6483,
        107.2605,  78.2783, 100.8736,  27.6843,  89.7511,  44.2258,  46.6286,
         78.0452,  70.1014, 174.3930, 127.5678,  42.0146,  64.6170,  56.6358,
        262.6860,  31.9806,   0.4609,   5.4534, 235.3581,  44.9784,   3.8368,
         58.1182, 158.8373,  34.8334, 146.0079,  41.0868,  13.3447,  62.8430,
        138.3154,  21.4452,  98.8750, 147.4204, 211.0492,  68.7182,  57.9332,
        329.9075,  33.6672,   7.1175,  36.2951,  97.6203,  25.7240, 101.8715,
         82.4268,  59.9959,  75.0514,  42.0783,  34.8677,  54.6486, 146.6441,
         78.3296, 251.6430,  87.3075,  90.2472, 202.6793,  27.2617, 272.1041,
         51.8549], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1], device='cuda:0')
tens

tensor([279.8118,  98.6393, 133.6828,  47.4252, 153.3710, 353.6444, 131.8275,
         90.6784,  36.2402, 122.4839, 419.4158, 129.3756, 219.8932, 146.0509,
         13.0407,  35.5411,  80.4296, 166.7889, 109.1032,  17.9556,  55.4660,
        158.9873, 173.7003,  26.4709,  40.1264, 109.0142,  12.3041, 185.6815,
         27.3820,  89.5395,  26.9477, 163.8385,  64.4043,  32.2931,  17.0906,
         46.1945, 188.5590,   4.0010,  34.4582,  44.3408,  76.1004,  51.3003,
         83.1560,  29.1371, 171.9755, 127.8231,  17.2074, 137.0556,  73.3841,
         96.9472, 115.9397,  69.5485, 119.4192, 124.7523,  45.6510,  36.7483,
        115.6570, 117.1467,  29.4437, 102.6860,  61.7673,  42.2507, 255.4670,
         31.0203], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1], device='cuda:0')
tens

tensor([109.9900,  44.5827,  50.1590,  59.1464, 214.5506,  37.9512,  -2.1814,
          4.3703,  42.6291, 123.0984,  12.5123,  30.8624,  52.9165, 160.3493,
         16.2129,  67.0151,   9.2308,  46.3336,   4.3678, 105.8375,  24.6984,
         40.6811, 123.7969,   3.5683,  53.7017,  11.6415,  99.8190, 129.7548,
         42.4058,  66.8795,  97.9286,  60.3143,  78.2055,  26.3097, 118.5996,
         52.6302, 300.1514, 114.1807,  65.9937,  37.1106,  14.6274, 130.4443,
         85.6371, 140.3567,  55.9922,   8.5939,  28.5736, 136.0733,  15.9938,
        102.4268, 177.1738, 171.0454,  35.5616,  12.3241, 124.4190,  88.8249,
        107.9335,  33.0258, 104.8328,  18.4800,  76.2993, 157.5546, 112.1868,
        103.0949], device='cuda:0', grad_fn=<MaxBackward0>) tensor([0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0], device='cuda:0')
tens

tensor([122.4503,  85.5202, 276.2321,  82.4413,  44.7327, 225.4706,  91.5967,
        121.5941, 299.1365,  48.7110,  70.7662, 135.6690,  49.2057,  38.1548,
         58.9903,  45.1381,  57.4608,  -0.4956, 113.6933, 121.1768,  34.8149,
         64.1349,  13.8520,  23.5100,  29.4898,  63.7480,  78.8034,  16.1861,
         89.7286, 229.1373,  85.2256,  54.4074, 159.8530, 133.4379,  17.9547,
         25.8272,   6.4939,  35.1033,  47.3272, 239.1114,  88.7312, 158.5371,
         67.1059,  26.5976,   4.3748, 179.2943,  12.0011, 225.6282,  26.0969,
         30.8680, 175.7214, 118.1449, 118.7103,  37.0342,  64.7428,  74.8890,
        191.2422,   9.7857, 105.8288,  74.3889, 112.1135,  73.5627,  86.3351,
         24.7125], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1], device='cuda:0')
tens

tensor([164.5383,  46.5106,  27.6618, 167.3868,   7.0062, 231.4209, 138.7008,
         59.5718,  28.2691, 105.6769, 138.0683,  11.6935, 189.7869, 104.7124,
         77.6814,  99.0264,  85.0602, 114.4660,  39.2035,  13.8182, 206.8463,
         54.6507,  96.2691, 338.8120, 137.5342, 143.0791,  29.7767,  10.5194,
         65.1842, 286.7390,  86.4684,  47.6911,  67.8047, 118.4111,   9.2592,
         22.1382,  94.9368,  14.1125, 181.5845,  54.4348,  65.5746, 128.7905,
         21.8948,   1.9175,  13.6860, 216.3335,  34.4803,  63.9468,  34.1472,
        114.8238, 107.0469, 102.6420,  45.4448,  54.5568,  -2.8706,   7.0847,
         43.0202,  65.8086,  93.7512, 147.4375,  29.3875,  49.4923, 154.0668,
         36.8035], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
        1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1], device='cuda:0')
tens

tensor([ 12.3168,  43.0636,  20.0053, 176.7721, 226.4778,  13.5789,  81.9112,
         17.0004,  99.0308,  83.5595,  63.4236,  13.2662,  57.0394, 129.3354,
        157.8296,  22.6157,  86.1967, 195.0799, 131.7637,  17.3877, 178.6227,
         19.7284,  22.4886,  95.6397,  61.4599,  31.1438,  74.5000,  47.0144,
         94.2389, 114.6863, 164.9104,  10.3878,  -2.3049, 147.7559,   3.6284,
         51.7735,  35.3260,  13.9531,   7.6336, 151.6619,  56.4941,   4.0778,
         66.5025,  47.9591,  52.8975, 185.1736, 114.9979,   6.7945,  83.4512,
        138.0535, 179.4293,  95.9909,  72.6779,   9.2733, 108.8410, 215.2155,
         86.2910, 123.4096,  80.4948, 177.9833, 107.7668,  83.8769,  56.7392,
         77.4657], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0], device='cuda:0')
tens

tensor([140.9417,  69.4410, 240.0980, 200.3557,  32.2546,  72.4657, 193.7677,
         26.3577,  17.2684,   5.3938,  24.2263, 120.1211,  66.3252,  68.6018,
        179.6095,  22.7566, 120.8135, 130.3469,  98.3678,  78.4746,  28.6416,
         81.0602,  92.1670, 181.4956,  35.1056,  49.6241,  48.8758,  88.6786,
         55.6080, 103.2013, 155.8244,  15.7121,  54.4295,  45.0061,  53.4280,
        119.6951,  38.3677,  20.4711, 182.4610, 137.0158,  33.5929, 194.9923,
         72.3305,  96.6906,  14.0712,  70.0359, 144.7437, 123.9839, 179.0760,
         34.2240, 161.7155, 111.8604, 159.9273,  80.8224,  49.1108,   3.7246,
        110.1943,  18.1492,  11.8644, 193.3075,  29.1918,  54.5432, 110.9129,
        131.6315], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1], device='cuda:0')
tens

tensor([ 26.6739,  53.3142,  41.4002,  64.1920,  74.2893,  64.4574,  86.6396,
        157.4095,  93.1827, 117.4753, 255.4491, 147.7011, 143.2547,  48.7836,
         75.3888,  39.8293,  51.6853,  20.6443,  90.6537,  81.5139,  14.7888,
        111.3146,  56.4280,  11.8714,   4.0028,  30.0625,  93.6717,  12.7667,
         64.2488,  13.5146, 103.8637,  18.9719,  38.8138,  11.9492, 135.5234,
        154.3359, 141.8324,  36.4934,  55.4563,  67.9435, 144.9970, 195.6537,
        273.8350, 154.6543,  54.1602, 102.7911,  32.7640,  47.5269,  19.3692,
         81.6091,  22.0716,  49.3837,  33.1487, 131.2520,  68.9155,   8.4878,
        146.8227,   9.1417, 111.8303, 118.3713,  26.7099,   1.3445,  61.6208,
          4.0115], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
        1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1], device='cuda:0')
tens

tensor([1.9954e+02, 1.5824e+02, 1.3938e+02, 6.0989e+01, 1.5693e+02, 5.2086e+01,
        8.0137e+01, 4.2026e+01, 1.1254e+01, 2.0022e+02, 8.2680e+01, 6.5525e+01,
        7.6940e+01, 1.2329e+02, 6.0232e+01, 8.8243e+01, 5.9000e+00, 3.1789e+01,
        3.6705e+01, 4.4824e+01, 1.9850e+02, 4.2508e+01, 1.8158e+01, 3.4873e+01,
        2.9743e+02, 8.0475e+01, 6.9734e+01, 6.4458e+01, 1.0843e+01, 5.9424e+01,
        2.3072e+01, 5.9084e+00, 5.1566e+01, 7.7437e+01, 6.4323e+01, 3.2129e+01,
        3.7140e+01, 1.3694e+02, 5.4233e+01, 2.5445e+01, 5.2648e+01, 1.7531e+02,
        7.6445e+01, 1.0637e+02, 2.5296e-01, 1.4598e+02, 4.7542e+01, 1.3515e+02,
        9.9896e+01, 4.5067e+00, 1.2457e+02, 6.0186e+01, 2.4961e+02, 1.3832e+01,
        1.7360e+02, 8.5916e+01, 2.0871e+01, 3.9054e+01, 2.0109e+02, 2.0794e+01,
        3.6560e+00, 1.4367e+02, 7.8119e+01, 9.8613e+01], device='cuda:0',
       grad_fn=<MaxBackward0>) tensor([1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
        1, 0, 0

tensor([183.8807, 144.8455,  48.2861, 241.4485,  31.9473, 114.9509, 306.0376,
         64.0385,  43.8365,  58.2464, 196.9818,  61.9931,  22.4005, 112.3493,
         62.7943, 162.8356,   6.4414,  19.6044, 206.2084, 152.0331,  86.3108,
         33.5187,  21.9389,  14.2472,  46.0148,  46.3444, 186.6188, 240.5773,
        175.6213,  42.9653,  62.1599,  44.5737, 167.2678,  98.7620,  56.9248,
         47.9053,  85.1788,   6.0581,  76.9493, 151.0580,  76.0744,  93.7253,
         31.7498,   4.8706, 146.1945, 117.5809,   8.9248,  33.3910,   1.5437,
         12.7937,  11.4427, 118.7562, 153.0554,  57.2796,  61.3764, 168.8140,
         68.3856,  60.7383,  15.6988, 100.0522,  47.2203, 183.8666,  26.4231,
        175.9255], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
        0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1], device='cuda:0')
tens

tensor([ 47.9062,  94.4486, 205.5437,  62.2316,   8.5960,  93.8184,  51.6354,
         61.6931,  23.3733,  59.3686,  62.4846,  61.5356, 157.5733,  18.2827,
        162.8650,  50.1801, 128.7652, 111.1638,  96.6739,  52.0425,  90.3698,
         23.9400,  60.2021, 105.3945, 184.8907, 126.9026, 140.6384, 133.8360,
         93.8617,  66.2026,  13.0664, 203.5154,  22.6947,  13.6828,   6.0177,
         40.3472, 114.4320,  22.6955, 124.1421,  56.2472, 114.8217,  48.8400,
          8.6909, 123.7881,  67.9139,  56.6903,  49.2964,  15.1578,  18.5771,
         63.4075, 118.3619,  68.0093, 136.1815,  11.3947,  78.4484,  50.4657,
         88.6746, 128.7772, 125.4142, 103.4186,  62.9361,  97.6990,  60.2273,
         63.1455], device='cuda:0', grad_fn=<MaxBackward0>) tensor([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0], device='cuda:0')
tens

tensor([  9.1260,  57.2742, 113.0766, 112.9116,  94.0420,  75.1712,  31.2214,
         96.5372,  58.7773, 268.8563,  31.7428,  35.1042,  97.9779,  55.2538,
         41.9411,  15.8655,  21.5868,  12.2458, 122.4342,  13.1907, 161.7247,
        247.1060, 169.2376, 193.2263, 164.7749, 157.9573,  58.1434,   9.3389,
         48.3750, 104.1757,  57.3725,  34.4065,  74.7379, 101.2454, 119.4718,
         12.4655,  36.0412,  -1.3828,  27.6917,   9.5765, 165.7727,  19.6821,
        137.1982,  78.7746, 146.9940, 151.6240,  53.9697, 230.8320,  79.0028,
          6.3852,   8.9064,  41.9235,  64.8714, 111.7714,  61.1208,  25.2806,
         35.2044, 116.1292,   7.8714,  50.5605,  20.6108,  22.8159,  18.9765,
         84.9693], device='cuda:0', grad_fn=<MaxBackward0>) tensor([0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0], device='cuda:0')
tens

tensor([113.1201,  66.2576, 283.4020,  93.1010, 164.2714,  59.5419,  84.1303,
        121.5353,   5.0838,  79.6897,   3.7164, 103.7089, 123.2590,  68.6263,
         51.9851,  86.6649,  39.0721,  42.5551,  30.6626, 158.1262, 185.7122,
        110.4274, 209.0194,  80.1674, 142.6767, 110.1525,  89.4649,  86.5434,
        108.8196,  74.0960,  27.8955,  -3.2952, 153.2117,  34.6465, 123.9186,
         59.9966,  38.6640, 151.1586, 112.9135,  35.4545,  11.3241, 150.3195,
        188.7848,  79.3536, 195.7075,  12.8531, 152.7092,  29.5656, 181.9577,
          9.6742,  77.8075,  79.1195,  48.7236,  88.1792, 189.4164,  57.5147,
        138.0526,   1.5027,  58.9901,   4.8474,  85.2245,  71.5048,  -4.5338,
         12.9527], device='cuda:0', grad_fn=<MaxBackward0>) tensor([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0], device='cuda:0')
tens

tensor([235.5547, 179.3714, 158.4747,  89.9985,  51.6450,  43.0759,  32.9563,
         18.7763, 199.0506,  82.0232,  35.0345, 157.0404, 206.6522,  82.9686,
         88.9251,  43.1610,  70.4782,  53.1880,  74.4871,  34.4401, 135.0092,
         22.1249,  31.4267,  75.7289,  65.5094,  99.3661, 135.9237,  52.9867,
         83.9696, 174.5866,  41.0640, 133.6984,  35.0867,  33.2627,  36.5958,
         91.6067, 224.1582,  73.0285,  72.4299,  36.0373,  50.4504,  74.4937,
        103.7957,  97.9211,  89.1663,  69.6567,  31.6029,  54.3508,  92.2146,
         67.0042, 130.3739,  62.0307, 346.9832,  98.4232, 140.5030, 249.5249,
         37.6574,  24.0497, 147.8261,  86.3464,  98.6460,  95.0187,   3.5647,
         20.5748], device='cuda:0', grad_fn=<MaxBackward0>) tensor([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
        0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1], device='cuda:0')
tens

tensor([ 44.1109,  17.7955,  37.0127, 148.4879,  56.2906,  19.7374,  30.3007,
         82.8724,  82.7892,  76.1083,  36.1404,   2.1596,  82.4364,  50.3957,
         86.1490,  67.0511, 135.0942, 177.3738,  -1.6838, 103.8406,  64.2811,
         32.1383, 162.1523, 153.5234, 225.4826,  25.4035, 208.8172,  56.8102,
        160.7300,  -0.7580,  90.9927, 185.9953,  43.7770,  -4.7059,  59.0233,
         29.9519, 117.2257,  96.7991,  86.1714,  32.5868,  47.6826,  40.2846,
        228.9830,  78.4467, 104.8382,  94.7614,  33.8094,  77.4335,  28.3798,
         24.7892,  71.1379,  28.6108, 213.5852,  55.1651,  13.6324,  63.8657,
         73.0726], device='cuda:0', grad_fn=<MaxBackward0>) tensor([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
        1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 0, 0], device='cuda:0')
tensor([106.0714, 101.6098, 191.1203, 401.2484,  83.8898,  61.9120, 137.3205,
        154.7011, 160.818

tensor([ 70.9761,  82.4973,  52.5630, 112.1982, 106.2966,  74.8085, 130.9186,
         86.4906,   0.7797,  85.6955, 202.1416,  82.5523,  90.1349,   0.9625,
        167.0973, 232.2516,   6.1124,  44.5362,  78.6500,  14.9041,  61.4825,
        123.7103,  62.9304,  55.0830, 142.7296,   1.8016,  27.9074,  51.0173,
        145.2947,  32.1851, 129.0114,  60.4863,  16.5486,   2.8413,  63.2801,
         93.7295,  21.8871, 137.4206, 112.7125,  97.1866,  64.2770,  73.9549,
        124.3155,  88.7314,  37.9658, 168.6526, 130.0890,  26.9772,  50.7038,
         35.2856, 106.6983,  18.5365, 192.9134,  43.9120, 178.9943, 198.4026,
         80.4486,   5.9132,  40.1132,   3.8299,  22.7822,   2.1765,   4.8262,
        108.6824], device='cuda:0', grad_fn=<MaxBackward0>) tensor([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
        1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0], device='cuda:0')
tens

tensor([1.5704e+02, 2.0041e+02, 7.1749e+01, 2.7045e+01, 2.7340e+00, 2.3901e+01,
        8.4056e+01, 9.9051e+01, 4.0452e+01, 1.5775e+01, 4.9937e+01, 1.7681e+02,
        5.5299e+01, 8.6724e+01, 4.3362e+01, 7.6644e+01, 7.5022e+01, 1.8950e+01,
        4.8981e+01, 1.2000e+02, 8.5138e+01, 1.6927e-01, 1.2945e+02, 1.5565e+02,
        9.6150e+01, 3.0763e+02, 1.3046e+02, 3.9773e+01, 8.4577e+01, 8.7531e+01,
        1.6181e+02, 4.9546e+01, 7.7843e+01, 4.8443e+01, 7.6910e+00, 4.3865e+01,
        1.2769e+02, 1.4101e+02, 8.8242e+01, 8.9680e+01, 1.0281e+02, 2.0627e+01,
        3.9393e+01, 1.0769e+02, 2.9216e+01, 1.1854e+01, 5.3689e+01, 1.3842e+02,
        1.1399e+02, 2.4314e+01, 1.4775e+02, 7.3787e+01, 9.5129e+01, 1.3944e+02,
        1.4986e+02, 1.4203e+02, 3.7555e+01, 1.3338e+02, 2.3744e+01, 9.7062e+01,
        9.6516e+01, 6.6041e+00, 8.8520e+00, 5.5632e+01], device='cuda:0',
       grad_fn=<MaxBackward0>) tensor([1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
        0, 1, 1

tensor([ 15.4722,  69.9038,  32.5604, 113.1581, 100.2465,  69.7221, 268.7912,
         23.0950,  66.5942,  71.7288, 114.2731,  10.9778, 149.6468,  38.0121,
         86.5692,  81.0928,  28.8145, 118.6017, 120.0090, 228.9840,  65.4451,
         40.1284, 184.9871,  62.8731,  90.1598, 120.1361, 160.6900,  15.2355,
        196.7710, 169.8108,  12.2110,  -3.5420, 148.2672,  29.9751,  46.1842,
         16.8960,  61.4476, 109.9090,  30.8048, 112.7435,  47.5736, 152.9171,
        105.9818,  18.8117, 104.3467, 184.9588,  45.4685,  76.7257,  51.5818,
         34.2121, 165.3138, 104.0649, 127.5794,  79.6327,  66.3521, 110.9368,
         97.0034, 100.2020,  26.6833,  -3.9319,  46.8692,   4.0474, 116.7354,
         19.8034], device='cuda:0', grad_fn=<MaxBackward0>) tensor([0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1], device='cuda:0')
tens

tensor([48.1008, 24.9834,  1.8049, 28.8824, 38.7522, 51.9607, 22.7618, 22.0850,
        29.5424,  8.9305, 28.5157, 19.1988, 20.8228, 14.6029, 17.3696, 40.4110,
        21.8744, 18.6122, 31.0906, 25.4268, 33.1003, 38.2182, 37.5774, 28.0375,
        10.4599, 28.3727, 38.0802, 43.8595, 24.4101, 17.3194, 23.9293, 34.4453,
        54.9786, 53.4240, 11.9352, 33.8849, 22.8502, 21.9211, 14.5500, 16.0285,
        52.6977, 23.7193, 39.8066, 47.1237, 19.5157, 31.4603, 36.2356, 14.8249,
         6.5054, 21.1304, 34.3960, 36.2115, 31.7749, 29.1690, 22.2270, 24.2723,
        42.4734, 32.0048, 21.4349, 35.6590, 35.4592,  8.1394, 22.4059, 24.2421],
       device='cuda:0') tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([28.6422, 26.2819, 21.7641, 22.6770, 32.6933, 18.5641, 45.3797, 13.0846,
        32.9060, 18.1

tensor([50.6377, 28.7481, 23.9237, 46.4947,  8.9567,  6.4381, 18.8089, 42.0997,
        21.3303,  8.7817, 38.4744, 27.3812, 47.6186, 51.0012, 37.5145,  5.3779,
        10.4399, 22.2741,  8.6409, 26.2682,  5.7715,  8.1777,  6.1409, 23.5497,
        12.4648,  4.9366, 47.1867, 17.3563, 11.1324, 14.2764, 24.1530, 20.5383,
        30.0490, 27.7322, 34.0237, 11.3127, 19.4143,  6.9206, 28.4601, 16.7341,
         8.9022, 10.2868, 29.5053, 19.1850, 50.4152, 54.8252, 30.3558,  9.3574,
        12.1866,  2.6156, 16.7681,  6.9258, 27.6625, 28.4659, 21.1005, 30.8713,
        26.3765, 23.2696, 29.6006, 28.9555, 59.8307, 11.6675, 17.5346, 25.3864],
       device='cuda:0') tensor([0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([ 7.4183,  5.9390, 26.8896,  4.6631, 50.6877, 26.6853, 22.0594, 27.3444,
        19.4358, 18.6

tensor([34.1833, 24.7770,  6.9513, 27.5208, 42.0661, 15.0084,  3.9320, 13.9426,
        22.3853, 27.6319, 23.4757, 14.1466, 19.7808, 28.9834,  5.9473, 35.1887,
        49.7728, 32.3623, 37.9972, 46.0478,  2.2729, 20.0765, 23.0828, 30.5145,
        22.2508, 14.9038, 22.3977, 28.7868, 14.7291, 36.3203, 18.5837, 28.5201,
        61.6977, 42.1949, 18.2458,  5.3660, 28.7287, 19.6582, 29.5254, 34.7403,
         5.1740, 26.4854, 33.9231, 31.4209, 26.7865,  6.4853,  7.6840, 27.5797,
        29.2712, 25.6353, 25.0956, 22.1045, 29.7406, 62.3615, 26.4209, 33.9847,
         1.1581, 36.3308, 47.5695,  3.2002, 36.8592, 37.3629, 30.6220, 15.0892],
       device='cuda:0') tensor([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], device='cuda:0')
tensor([27.1408, 49.9300,  9.2134, 22.0017,  6.5373,  0.7301,  7.9289, 13.5053,
        20.1675, 13.8

tensor([37.1820,  1.7169, 15.2949, 30.1920, 28.0164,  4.5024, 11.2384, 25.1953,
        29.9846, 16.1997, 35.3854, 29.4954, 15.3015, 28.3680, 22.0542, 51.5466,
         4.0683, 33.1635, 18.6947, 49.2946, 15.6187, 14.1695, 34.2681, 15.9114,
        36.7436, 36.9538, 16.6914, 32.0894,  2.9642, 61.6019, 38.5884, 26.8188,
        35.8248, 37.5194,  0.7825,  4.4048, 20.0435, 28.2074, 29.7058,  7.4538,
        23.3750,  9.6009, 35.6862, 35.9447,  0.9024, 36.5645, 39.2428,  7.1417,
        44.3617,  1.0526, 37.3278, 25.2400, 23.9245, 40.8545, 53.6728, 41.0842,
        24.3179,  8.4804, 28.6493, 32.1054, 28.4089, 11.9923, 32.4275, 23.8249],
       device='cuda:0') tensor([0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], device='cuda:0')
tensor([31.2470, 17.2478, 28.0245, 19.3572, 25.2652, 55.2504, 30.5835, 27.3501,
        44.4121, 39.7

tensor([10.1869, 25.7859, 43.5793, 28.1308, 14.0580, 27.5146,  7.4271, 48.2475,
        41.1294, 42.1415, 42.5939, 29.4348, 14.6142, 19.4355, 20.0384, 32.5114,
        31.0094, 12.7468, 25.1755, 15.2614, 16.0373, 23.0240, 17.5479, 29.7772,
        25.1636, 36.4501,  9.8538, 13.2382, 15.6935, 22.1602, 56.0223, 28.0661,
        28.5743,  2.3838,  6.4727, 46.5990, 23.1627, 58.3608, 28.5412, 35.6025,
        56.5766, 13.6015,  7.1698, 35.2265, 34.8162, 46.9390, 28.6614, 48.5345,
        34.1656,  1.7629,  4.9220, 23.9030, 26.5002, 28.2394,  5.9187,  0.8178,
        18.2791, 29.2557, 22.5978, 42.3119, 23.4524, 19.6225, 14.4757, 32.5225],
       device='cuda:0') tensor([1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0], device='cuda:0')
tensor([52.9488, 27.7536, 27.6324, 26.2226, 23.5418, 33.6395, 13.9969, 13.0777,
        14.0488,  4.4

tensor([23.5115, 23.4634,  7.1065, 11.5191, 18.1635, 31.2761, 22.9980, 32.0048,
        23.7746, 15.6153, 22.1967,  7.6702, 35.5681, 30.4547, 29.5517, 38.6035,
        51.9998,  7.4056, 16.7882, 34.8958, 10.4514, 25.2717, 48.1027, 26.4294,
        19.6962, 20.6593, 10.1294, 64.5375, 17.2229, 28.7074, 30.9376, 11.9887,
        32.9921, 26.4791, 14.8388, 35.3541, 25.1911, 10.5133, 25.6833, 29.1178,
        12.3520,  8.2108, 34.3360, 54.2550,  6.2135, 23.5457,  6.0588, 25.1625,
        12.6627, 24.1423, 28.4876, 45.0624, 13.4220,  5.6222, 10.4263, 13.7093,
        37.0959, 24.9981, 24.6692, 23.6232, 11.2587, 22.6781, 25.2527, 13.9389],
       device='cuda:0') tensor([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0], device='cuda:0')
tensor([21.1433, 14.3113,  7.2534, 18.1259, 50.5473, 51.9987, 31.7118, 19.7224,
        49.9629, 18.2

tensor([23.9894, 12.2289, 12.1709, 42.3028, 29.6975, 24.5545, 36.2021, 36.6240,
        19.2451, 25.4000,  1.1363, 18.4016, 11.3670, 36.1615, 58.9308, 17.4870,
         1.7350, 23.2157, 30.3910, 13.5371, 17.4482, 15.9040,  2.0290, 27.5053,
        34.9814, 39.5311, 49.8205, 20.3039, 17.5859,  3.2087,  3.5513, 31.0254,
        17.0190,  8.5182, 27.9013, 11.3602, 26.3358, 35.5526, 22.2111, 34.6352,
         2.3487,  5.6082,  9.5101, 27.5302, 16.3874, 18.4197,  4.2981, 38.2494,
        41.2800,  1.4534, 20.4374, 20.2652, 14.5765, 23.2601, 40.0268, 21.1334,
        20.3979, 16.0081, 14.7120, 25.1797, 11.9177, 19.9136,  6.5024, 20.8851],
       device='cuda:0') tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0], device='cuda:0')
tensor([13.8906,  3.3779, 14.7794, 35.4680,  6.9417, 19.5991, 13.4621, 35.5738,
        29.3937,  7.1

tensor([ 1.5608, 46.3452,  2.6480, 30.6095, 22.4764,  9.6262, 21.5969, 23.3075,
        31.8910, 45.8614, 38.8760, 16.0883,  5.8468, 11.2102, 43.4048, 27.6419,
        29.2108, 24.6027, 23.6001, 13.2522,  7.9635, 27.2349, 25.3871, 14.9250,
        31.6356, 24.9021, 55.1201, 24.7307, 12.8394, 11.1176,  7.9285, 15.9297,
        51.8932, 13.6531, 50.8793, 17.8557, 54.1272,  0.9611, 12.5584, 25.9868,
        36.0996, 26.7240, 32.5081, 30.2927, 51.2110, 13.3502, 26.0422,  1.3543,
        36.2993, 29.1452, 29.0292, 22.9893, 40.6786,  1.8066, 43.0560, 12.9432,
         7.4410,  6.0900,  5.3238, 31.3886, 43.8837,  7.0783,  9.0457,  1.6593],
       device='cuda:0') tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1], device='cuda:0')
tensor([19.6900, 26.5634,  4.8305, 30.1347,  9.7712, 22.9097, 25.9687, 38.6341,
        42.8330, 29.3

tensor([ 3.2406, 15.8349, 13.9932,  4.7806, 36.4221,  1.9826,  4.3758,  5.7930,
        29.5507, 27.3097,  2.4258, 43.4470, 35.9820, 18.6541, 30.9755, 39.3102,
        18.7279, 18.1627, 12.3089, 40.6719,  4.0718, 22.2418, 28.1234, 42.7635,
        42.8637, 42.0085, 34.8451, 51.8944,  5.3332,  5.7716, 12.8579, 21.0323,
        23.5850, 28.8547,  7.2008, 18.1824, 43.0845, 16.8845, 22.7628, 16.0150,
        36.4645, 30.7110,  8.2832, 24.3903, 11.0444, 28.2744, 19.8636, 55.3761,
        28.2383, 23.4384, 25.3755,  3.2684, 17.8718, 52.2355, 17.4560,  5.1224,
         4.7143, 19.0631, 10.3440, 15.2209,  2.7649,  1.1285, 36.4233, 28.9269],
       device='cuda:0') tensor([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1], device='cuda:0')
tensor([29.7132, 17.1392, 27.1811, 22.8704, 17.3577, 22.1819, 13.6080, 43.2754,
        18.9623, 21.0

tensor([ 1.4513, 48.6230, 26.9325, 24.7625, 46.1771, 14.3097,  7.1646, 24.0552,
         1.5277, 32.4276, 32.9215, 12.2333,  5.4664, 22.2522, 33.2474, 24.7496,
        32.2552, 44.7654, 14.6076, 23.6587, 37.9841,  8.4500, 19.7442, 30.7090,
        33.9313, 26.5743, 27.6611,  8.6326, 24.9850, 33.9770, 16.8986, 30.5978,
        22.2745,  2.1883,  4.8248, 41.8963,  2.9820, 22.8454, 37.7056, 32.9541,
        51.0222, 24.2933, 16.3413, 34.8221, 23.9192, 34.2952, 21.1583,  2.5597,
        16.7599,  4.9093, 18.6395, 18.6170,  3.4955, 52.5740, 29.1493, 24.1494,
        13.1613, 35.1293, 51.2892, 19.9884,  3.2978, 15.1892, 22.0041, 23.2298],
       device='cuda:0') tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([18.5443,  3.7873, 20.9287, 10.3440,  4.1395, 30.0068, 10.8856,  7.3723,
        35.4804, 20.2

tensor([28.4545, 15.2733, 20.4128, 40.9650, 31.3477, 34.8215, 36.6187, 27.8028,
        24.3367, 38.0986,  3.7078,  2.6732, 25.6606, 15.0472, 17.3011,  4.8425,
         7.2216, 10.9258, 43.4882, 14.3333, 20.4389, 37.2496, 28.7740,  6.9622,
        36.2410, 13.0842,  1.0570, 10.7871, 19.4245, 32.6707, 17.6724, 24.4372,
        31.0959, 50.5340, 17.7559,  8.1288, 22.0516, 14.3355, 44.7682, 41.6188,
        28.0603, 31.8048, 15.6507, 26.6032, 41.5776,  2.6165, 38.8717, 25.7728,
        15.5880, 33.6572, 26.4770, 24.4871,  3.3996,  3.6977, 37.6231, 26.5962,
        59.4401, 39.2629,  3.2108, 16.4613, 52.7527, 20.6927, 18.7492, 18.1758],
       device='cuda:0') tensor([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1], device='cuda:0')
tensor([31.3621, 20.3068, 14.7195, 27.6793, 16.1835, 17.1400, 27.1691, 15.5989,
        28.4065, 18.5

tensor([39.2524, 31.5077, 44.7699, 14.1662, 21.1753, 31.6078, 24.1362, 27.3464,
        45.3659, 19.7179, 15.1253, 38.0010, 51.6503, 40.0189, 30.5952, 14.3194,
        48.4132, 14.9906, 29.1529,  6.3091, 12.3336, 10.4081, 14.0080, 39.0676,
        27.6850, 20.5700, 13.1005, 26.4723, 11.8791, 38.2808, 19.0670, 16.5310,
        32.7318, 23.4200, 16.7123,  5.8732, 19.0298, 27.6457,  8.7321, 18.3562,
        25.0836, 10.8826, 17.7211, 20.6131,  3.1733, 26.9324, 17.4539, 64.4966,
        30.4408,  1.1591, 19.0460,  5.4988, 28.2104, 21.8247, 44.2211, 31.1250,
        18.1349,  2.1795,  6.7921, 14.0156, 29.4632, 15.5171, 15.2324,  4.9385],
       device='cuda:0') tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0], device='cuda:0')
tensor([24.7729, 18.0622,  8.6641, 15.8276, 22.1506, 34.1963, 29.9480,  3.2673,
        19.7550, 12.2

tensor([ 9.4440, 37.6656, 30.1450,  5.3280, 18.2090, 54.8801,  5.4335, 27.0347,
        18.0252, 63.6106, 11.9683, 37.3196, 27.7061, 29.6369, 39.7306, 43.7670,
        35.9459, 53.7497,  8.4706, 20.3852, 50.6454, 14.6542, 17.7606,  2.9272,
        37.2659, 23.0533, 25.2596, 13.5854, 23.2989, 16.6998, 45.3957, 28.9757,
        16.3915,  5.7417, 17.6510,  4.2118, 31.0111, 28.3978, 50.7088, 37.3058,
        21.8789,  3.3822, 17.4854, 11.7775, 26.4246, 28.4272, 31.5897,  7.8939,
        18.8977, 10.4168, 10.7102, 13.7824,  1.7458, 15.3000, 30.3958, 16.8281,
        31.9332,  9.7435, 56.9530, 60.6920, 28.0826,  3.7794,  2.7802, 23.2925],
       device='cuda:0') tensor([0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1], device='cuda:0')
tensor([21.3613,  2.9036,  4.9589, 10.8357, 12.9586, 19.9795,  9.7486,  7.2122,
        10.4657, 27.7

tensor([21.1168, 30.9245, 20.1938, 44.4587, 40.8060, 22.0004,  3.7869, 17.9628,
        28.4486, 27.9961, 23.8379, 25.1425,  1.2740, 17.2745, 28.2355, 41.4526,
         4.3677, 17.8545, 25.1008, 21.3383, 22.8457, 15.1529,  5.8397,  1.4812,
        33.5394, 19.2778,  6.4273, 44.0916, 52.0072, 23.9865, 32.4041, 25.0759,
        32.6130, 17.5359, 10.0105, 14.7442, 43.0723, 17.0255, 30.0156, 44.6937,
        45.6145,  2.1122, 24.3950, 19.8695, 30.1727, 22.6499, 51.9325, 14.9551,
        23.8933, 21.7264,  3.6627, 13.9114, 24.9624,  3.2820,  7.7515, 47.1328,
        50.8108,  5.7308, 15.3736, 41.9754, 13.8415, 34.1375, 21.7780, 48.3397],
       device='cuda:0') tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0], device='cuda:0')
tensor([ 1.6568, 25.1309, 20.6972, 19.2554, 29.9801, 23.3845, 28.3570, 33.0955,
        51.4729, 36.9

tensor([42.8024, 26.8710, 28.8213, 33.2741, 14.8593, 14.2950, 49.0072, 31.6273,
        10.3318, 16.3587, 13.7044, 29.4549,  2.1792, 24.5197, 44.0867, 25.4898,
         9.6469,  9.0113, 58.0356, 51.3416, 28.4944, 33.0419, 45.1155, 24.2886,
        14.0251, 26.5458, 23.9997,  1.5606, 43.9475, 44.5435, 35.1942, 23.5158,
        15.2780, 38.9770, 44.2332, 29.2330, 40.3238, 19.3237, 13.9973, 29.2741,
        18.5613, 57.4232, 13.6374, 15.9092, 42.3631, 26.2335, 38.3669, 40.5571,
         1.3358, 22.5200, 26.4090, 23.6922, 33.1385, 13.0951, 27.5651, 15.3423,
        32.9969,  2.1048, 28.6991, 33.2915, 30.0346, 17.8749, 24.1921, 16.3074],
       device='cuda:0') tensor([0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([27.6006,  1.7468, 23.0422, 13.8990, 18.0002, 29.2495, 11.3012,  4.7009,
        18.2221,  5.2

tensor([25.8946, 53.5867, 35.2087, 18.4182, 17.0198, 39.7973, 25.6090, 27.6080,
        40.1016, 46.1121, 28.7610, 22.2200, 40.8702, 24.7674, 19.5724, 29.8147,
        33.9125, 28.5249, 34.2050, 23.2859, 22.2627, 22.8481, 58.0645, 20.6355,
        14.8614,  3.5594,  1.5350, 19.4617, 29.9171, 19.1394, 30.0834, 31.1815,
         9.1361,  6.1018, 34.6527, 34.1211,  0.7704, 20.8520, 29.8783, 27.9813,
        29.5452, 29.1756, 37.2761, 27.0677, 12.7157, 10.9833,  7.0632,  0.7987,
        25.6089, 21.7645,  3.4924, 24.3315, 11.8129, 13.2073, 29.7411, 24.1447,
        16.0353, 10.7005,  6.3176, 34.0839,  3.9345, 20.7315, 27.0189, 20.5372],
       device='cuda:0') tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], device='cuda:0')
tensor([29.8373, 22.2414,  6.3063, 30.1775, 20.7024, 37.7326, 46.7820, 39.2643,
         3.1008, 15.3

tensor([33.7208, 14.2545, 38.0094, 52.0430, 10.2572,  2.3260, 31.8600,  3.8153,
        56.8681, 12.4132,  5.1273, 22.7624, 35.4115,  4.7663, 18.9573, 24.1127,
        28.0133, 16.2947, 38.3142,  9.3000, 47.9962, 35.0978, 56.7427, 24.3492,
        23.4801, 25.2411, 20.7084, 23.9568, 25.1591, 25.0385, 29.9023, 11.6884,
        23.5835, 19.7361, 36.5019,  3.1655, 27.6519, 20.6878, 21.1906, 46.9191,
         2.9039, 36.1943, 31.3487, 26.7110, 25.5407, 21.9637, 23.8194, 26.3842,
         6.8222, 26.4755,  1.7061,  9.8415, 29.7951, 11.1333, 17.5971, 14.9577,
        39.3437,  6.8899,  9.4544, 37.7317, 35.7197,  3.1923, 52.0996,  4.1305],
       device='cuda:0') tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0], device='cuda:0')
tensor([25.9947, 48.9589, 17.1794, 23.8155,  5.8110, 27.3542,  1.9268, 30.7896,
        16.9406, 42.1

tensor([ 7.6820, 20.5816, 12.9093, 15.9966, 42.1106, 46.3696, 28.2857, 20.1456,
        19.8230, 17.1485, 49.5471, 27.8885,  5.4749, 10.1353, 14.4690, 19.7037,
        30.9427, 35.4293, 20.7381, 56.5967, 36.2817, 38.1031, 28.7610,  9.5508,
        10.7597, 10.0971, 18.8596, 24.3462, 50.3195, 21.5413, 37.1169, 42.1458,
        29.1861, 12.3664,  4.3652, 24.7198, 44.3907, 14.7105, 19.8983, 23.4368,
        15.3131, 22.6325, 44.5010, 27.4315,  3.0323, 16.8502, 27.3500, 22.6181,
        10.2268, 40.7794, 22.8269,  9.3455, 12.9054, 33.4054, 24.4179, 21.3638,
        29.1361, 27.9884, 31.9112, 54.1832,  5.3080, 27.8870, 15.3885, 15.5418],
       device='cuda:0') tensor([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], device='cuda:0')
tensor([13.7407,  1.9298, 17.9580, 18.7949, 19.5321, 16.2438,  0.9634, 20.1513,
         2.0078, 38.8

tensor([31.9914,  8.1898, 29.4470, 17.9404, 32.5117,  7.0038, 42.9883, 22.8632,
        34.3374, 15.7728, 24.6896, 17.7348, 22.5500, 27.8997, 23.2170, 25.6066,
        58.0534, 13.3007, 50.8422, 10.6833,  1.8237, 33.4788, 15.5205, 19.3395,
        22.3454, 20.1166,  7.1292, 46.3555, 15.3948, 15.5802, 34.9206, 22.5997,
         4.0763, 24.9392, 50.6728, 24.9002, 24.4186, 41.9624, 31.6635, 33.7243,
        31.6519, 37.7987, 36.6899, 23.6790, 10.8777, 31.7946, 17.9648, 12.5749,
        15.6749, 25.4900, 21.9011, 15.0585, 18.2818, 41.7442, 32.3857, 40.4722,
        37.2488,  4.8210, 27.5358, 50.8119, 44.9932, 34.3616,  1.8202, 34.6288],
       device='cuda:0') tensor([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1], device='cuda:0')
tensor([15.4052, 17.4368,  1.7239, 46.0491, 29.2473, 27.0768,  6.7886, 32.7232,
        20.6079, 20.3

tensor([23.4031,  2.9732, 15.8027, 24.2659, 22.3683,  4.4653, 19.9480, 49.1295,
        18.4724, 22.3839,  9.5221, 13.4008, 51.5179, 27.8270, 17.9469,  3.7122,
        54.5812, 21.7018, 14.0824, 41.0484,  5.9592,  8.2999, 21.6268, 51.5276,
        34.4147,  5.3240, 26.0465, 21.7566, 21.9920, 20.6178,  3.3536, 50.3989,
        23.3572, 19.5696,  7.8658,  2.1424,  6.6639, 40.6656, 29.6876, 23.7050,
        25.3307, 33.3905, 25.4808, 22.5402, 11.4055, 45.4107, 25.3024, 42.6340,
        16.5305, 17.1395, 20.3928, 23.5980, 15.3771, 24.7933, 40.5324, 32.4885,
        16.8428, 18.4580, 10.6112, 28.5449, 22.7101, 50.7934, 10.5594,  5.9466],
       device='cuda:0') tensor([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([29.7520,  9.4352, 14.8770, 14.6374, 17.9034,  7.6922, 17.2564, 12.2810,
        17.2081, 23.7

tensor([32.2956, 24.3022, 55.3377, 13.9656,  6.4491, 14.6827, 31.0721, 26.4541,
        37.4009,  3.0841, 47.0641, 38.5090, 31.3002, 23.7111, 28.4356, 22.2147,
        46.3531, 27.7451, 37.8713, 30.9802, 21.9621, 18.2782, 40.6131,  3.8716,
        13.3042, 32.1666, 36.8663, 54.9508, 18.8277, 15.4294, 24.1198, 15.5959,
        12.8519,  1.5892,  6.8875, 12.1372,  5.4671, 31.5425, 13.5918,  2.2471,
         9.2451, 28.5863, 36.5746, 44.4792, 15.2394, 51.5616, 32.2931, 26.9989,
        24.7199, 10.6535, 24.6298, 15.7088, 12.1309,  6.1182,  4.3746, 48.7286,
        25.6185, 32.7468, 33.0456, 35.6355, 31.5992, 23.9136,  9.5030, 61.2533],
       device='cuda:0') tensor([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1], device='cuda:0')
tensor([20.9527, 16.7558, 58.3686, 33.3523,  1.3678, 10.1319, 18.0533, 19.0815,
         1.8098,  1.5

tensor([24.1500, 46.0511, 54.6443,  3.8792, 32.4975, 35.2795, 31.0222, 50.9802,
         5.0794, 12.7760, 39.7078, 17.1076, 22.9968, 20.8429, 22.0386,  9.9357,
        21.4411, 16.7871,  2.2400, 33.0826, 24.3872, 29.4688, 32.4551, 35.4389,
        15.8598, 39.8624,  9.7282, 38.4000,  8.5726,  4.7220, 17.1606, 14.7867,
        24.9772, 56.9076, 29.0276, 21.4036, 39.1094,  6.7959, 23.0487, 62.3734,
        28.3350, 10.5813, 35.4948, 22.2602, 26.8824, 35.0073, 12.0937, 27.0816,
        23.7117, 41.6348, 46.5826, 11.3556, 16.9791, 60.6140,  1.4763, 31.5582,
        23.7929, 17.5750, 31.0807,  6.7836, 26.4703, 19.8846, 22.7801,  9.6404],
       device='cuda:0') tensor([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1], device='cuda:0')
tensor([31.2454, 57.0798,  5.8776, 21.5562, 24.6875, 32.0717, 12.6074, 14.3929,
        15.6665,  9.9

tensor([27.8211, 20.2495, 33.4090,  0.1657, 33.1319, 10.0789, 15.3278, 65.7569,
        19.4150, 28.6451,  9.0213, 27.9580, 25.2990,  5.9030, 12.1180,  5.6106,
        24.5168, 41.7363,  7.1256,  3.2810, 48.1892, 29.5606,  4.0370, 16.9926,
        23.2142, 10.0924,  8.8804, 30.7269, 34.8638, 52.6221, 14.3694, 24.7695,
        15.5837, 69.7950, 24.9653,  6.8477,  7.5354,  8.4593, 39.1627,  1.3296,
         5.7640, 23.4415, 23.2139,  4.2076, 10.2881, 45.9273, 11.2483, 37.3226,
        23.3785, 25.9669, 11.3990, 16.5051, 28.7524, 27.9105, 40.9304,  8.7166,
        28.2218,  3.3030, 14.8494, 31.5184,  1.6451, 22.5927,  4.5831, 28.3118],
       device='cuda:0') tensor([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0], device='cuda:0')
tensor([27.1638, 26.9873, 19.8631, 31.7632, 49.7699, 54.7982, 34.0694, 21.1150,
        10.6322,  9.3

tensor([ 2.5849, 30.9261, 31.1863,  4.4113, 33.2028, 18.3305, 15.5641,  8.5281,
         9.7361, 46.8271, 52.5144, 10.5722, 25.7242, 19.9398, 28.4966, 17.5231,
        11.5059,  8.4156, 14.2889,  1.6997, 19.6882, 59.9168, 19.7405, 40.7167,
        24.3026, 13.8415, 31.2698, 13.3992, 23.9611, 27.0381, 21.1156, 20.4943,
        38.8835, 35.4796, 19.8883, 32.2828, 14.6322, 20.8792, 15.1361, 50.9516,
        11.1559, 17.1821, 30.8376, 44.3124, 33.3218,  5.2066, 11.3665, 27.4882,
         1.8488,  7.7531, 12.8914,  5.1659, 59.7193, 28.7242, 37.2206, 20.5553,
        22.8287, 50.9550, 16.2914,  2.6243, 36.6346, 17.0450, 10.6682, 26.6360],
       device='cuda:0') tensor([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], device='cuda:0')
tensor([19.1593, 28.7667, 23.0256, 14.0524, 37.5970,  3.6150, 16.3140, 27.3972,
        13.5695, 13.6

tensor([ 1.0943,  1.2744, 22.8945, 12.3817, 29.7617, 29.2319, 28.5224, 36.4067,
        27.7788,  5.2269, 15.4137, 25.6528, 15.9111, 24.3287,  1.7819, 35.4378,
        18.3537, 50.8477, 17.8904, 10.0164, 25.8020, 22.4997, 20.5041,  7.8469,
        28.5154, 41.0240, 41.8696, 22.6206, 29.0271, 36.4253, 15.6219, 19.7073,
        11.8573, 21.8131, 38.8242, 21.0832, 35.6541, 16.4873, 28.8822, 25.3731,
         3.5159, 61.2304, 38.5097, 40.7917, 37.1360,  5.1340, 21.6564, 47.7519,
        31.6252, 23.5160, 25.6768, 30.5874, 18.4652,  7.6340,  4.4611,  7.7882,
        14.9603, 38.2339, 31.4598, 16.0626, 36.2885,  1.0053, 21.6218, 49.5893],
       device='cuda:0') tensor([1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0], device='cuda:0')
tensor([ 4.2211, 31.8261,  8.5275, 22.6828, 12.6944, 29.3795, 30.4069, 33.3772,
        37.1529, 42.8

tensor([40.3620, 35.6006, 19.7627, 26.7600,  9.6812, 45.2935,  9.0437, 24.8878,
         7.2919, 11.0347, 24.8774,  3.7025, 11.5518, 40.4340, 28.0253, 26.7830,
        21.2812, 13.6577, 12.6392,  9.1641, 14.5961, 17.1863,  7.7709, 20.3427,
        10.6258,  3.4534, 25.5581, 19.7694, 30.6559,  8.8730,  8.2219, 27.3958,
        29.2382, 20.4603, 23.7072, 38.6312, 17.7870, 51.5874, 29.6100,  9.0542,
        30.6149, 14.7712, 38.1674, 18.4383, 45.2885, 49.3270,  4.7804, 35.0638,
        34.2992, 35.6922, 39.1426, 38.9889, 33.2729, 21.0096, 45.7068, 27.8158,
        29.3997, 27.4192, 36.1215,  5.1987, 17.1473,  9.1580,  4.7969, 15.2980],
       device='cuda:0') tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], device='cuda:0')
tensor([19.5257, 31.3556,  1.1001,  9.1369,  2.7970, 21.0475, 16.2833, 32.4887,
        18.4503, 35.2

tensor([16.8001,  5.4318, 33.5283, 40.2164, 28.4102, 40.3151, 26.4116, 22.5673,
        19.0694, 34.3396, 33.3910, 33.0381, 24.7837, 24.8612, 15.0252, 51.6717,
        33.1727,  5.4062, 29.9527, 39.4739,  9.7438, 12.3102, 60.2669,  6.0173,
        13.6125, 35.4098,  2.8233, 23.2487, 14.1687, 26.3453, 19.4556, 11.0299,
         1.6025,  9.3947, 10.3873, 24.3839, 25.2035, 45.3661, 25.0951, 26.6531,
        50.5921, 44.6768, 38.5029,  6.7377,  7.0503,  9.8835, 39.4744, 18.4774,
        42.2976, 26.0835, 15.6171, 24.5302, 30.7255,  7.5605, 47.8350, 24.5972,
        50.9473, 17.1856, 50.3300, 20.8469, 14.9410, 25.5764, 53.2129, 34.4294],
       device='cuda:0') tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([11.5719, 57.9188, 11.7541, 20.3913, 34.0600, 21.2954, 12.7330, 41.2842,
        30.6006, 11.7

tensor([ 5.0190, 27.4269,  6.7867, 36.3362, 30.6661, 31.2264, 19.3770, 10.4165,
         7.2213, 29.8963,  9.8873, 16.9908, 15.8355, 26.3528,  3.2470, 10.7742,
        36.1046, 16.5973, 17.4590, 47.5679, 12.1278, 33.5396,  2.7860, 30.5590,
         7.1426, 37.5624, 15.3671, 40.8060, 22.1018, 54.0853, 31.4767, 14.8470,
        20.9791, 19.6764, 39.7911, 23.3910, 25.8164,  6.9152, 16.7615, 40.8567,
        33.0266, 28.0213, 33.9597, 33.5122, 40.0984, 17.7759, 21.8765, 29.4707,
        23.1336, 23.8537, 29.2224, 27.7566,  3.9627, 15.5383,  8.3173, 32.0650,
        23.4029, 26.9368, 34.5159, 61.1881, 26.1112, 38.2846, 36.9410,  2.2070],
       device='cuda:0') tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], device='cuda:0')
tensor([29.0426,  7.1622, 38.9299, 27.7799, 17.6876, 15.6265, 11.3957,  5.3930,
        31.8910,  2.8

tensor([38.7907, 49.4307, 45.4227, 20.3980, 35.4114, 22.5612, 18.0945, 12.0844,
        11.9593, 25.9591, 34.9649, 55.5441, 40.4547, 30.9336,  3.8610, 40.2614,
        17.9506,  3.4934, 17.3509, 29.3439, 23.1260, 23.2872, 42.6667, 25.2064,
         9.3859, 14.6936, 16.2157, 59.6262, 28.0781,  8.5922, 20.3373, 31.2668,
        28.9893, 13.3980, 34.3031, 30.8446,  0.9568, 33.0465,  2.1573, 29.1852,
        32.2253, 28.3362, 32.8281, 30.7283, 32.8950, 23.2275, 21.2547, 10.0330,
        26.7985, 15.4776,  9.7265, 31.2172, 25.7373, 19.7430, 37.6782, 16.5642,
        48.9548, 17.1567, 17.2532, 32.3415, 42.0677, 26.8626,  4.7005, 31.9222],
       device='cuda:0') tensor([0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0], device='cuda:0')
tensor([28.6402,  0.4468, 25.4278, 23.5715, 17.0640,  1.1766, 38.5825, 36.9721,
        29.9571, 26.4

tensor([46.7658, 46.2161, 10.7785, 32.5918, 32.3164, 29.0620, 36.9119, 38.6811,
        25.0813, 12.1768, 10.9983,  0.8580, 13.3276, 18.5243, 22.4219, 14.9375,
        28.6686,  0.9213,  7.9907, 49.7283, 20.0269, 33.7028, 19.6401, 32.1263,
        16.9647, 37.1022, 28.0594, 11.2751, 29.6210, 54.0442, 32.8479, 30.5153,
         8.1839, 37.1084, 34.9043, 37.8775, 24.8318,  1.5560, 32.4073, 14.7455,
         8.5515, 26.0902, 15.5864, 21.4514, 24.7061,  4.5383, 22.0560, 19.0491,
         1.7087,  2.8976, 22.7183, 28.8809, 14.9621, 48.3180,  4.3235, 31.3489,
        30.9706, 36.7341, 33.8743, 20.9528, 24.5464, 16.3089, 12.4580,  5.7257],
       device='cuda:0') tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1], device='cuda:0')
tensor([26.2549, 36.1630, 11.8252, 37.7627, 32.1719, 20.8705, 22.8455, 30.0494,
        25.2706,  2.1

tensor([30.6025, 16.7264, 41.3512, 32.8755, 35.5536, 30.6377,  2.8218, 19.3238,
        18.3228, 15.6950, 13.2872, 22.4362, 37.2666,  7.1224, 37.9187, 10.9086,
        23.2112,  1.9284, 27.7063, 15.5346, 21.7227, 20.7168, 25.3703, 50.9764,
        11.1529, 22.3044,  9.6804, 18.8004, 16.1012, 18.2736, 28.8714,  2.3441,
         3.2359, 10.9128, 47.4038, 36.1251, 59.1816, 23.2381, 34.0174, 25.1962,
        60.1456, 10.8593, 25.2729,  2.4631, 23.6253,  4.4519, 34.9543, 33.1063,
        25.6075, 34.9142, 52.5764, 27.9491, 63.9978, 25.3673, 41.3418, 18.4318,
        46.6897, 37.6244, 12.3058, 15.6772, 44.2612, 36.7300, 31.7167,  1.6891],
       device='cuda:0') tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1], device='cuda:0')
tensor([ 3.2004, 13.9054, 24.8817, 18.2798, 41.9937, 20.8813, 35.1594, 40.2746,
        34.4403,  6.3

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace)
    (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (17): ReLU(inplace)

In [7]:
def train_model(model, criterion, optimizer, scheduler, num_epochs=25, chunks=9):
    since = time.time()

    best_model_wts = copy.deepcopy(model.state_dict())
    best_acc = 0.0
    
    for epoch in range(num_epochs):
        print('Epoch {}/{}'.format(epoch+1, num_epochs))
        print('-' * 10)

        # Each epoch has a training and validation phase
        for phase in ['train', 'val']:
            if phase == 'train':
                model.train()  # Set model to training mode
            else:
                model.eval()   # Set model to evaluate mode

            running_loss = 0.0
            running_corrects = 0

            # Iterate over data.
            for chunk in range(chunks):
                X, Y = torch.load('data/images-' + str(chunk) + '.pt'),\
                       torch.load('data/labels-' + str(chunk) + '.pt')
                train = data_utils.TensorDataset(X, Y)
                train_loader = data_utils.DataLoader(train, batch_size=64, shuffle=True)
            
                for inputs, labels in train_loader:
                    inputs = inputs.to(device)
                    labels = labels.to(device)

                    # zero the parameter gradients
                    optimizer.zero_grad()
                    # forward
                    # track history if only in train
                    with torch.set_grad_enabled(phase == 'train'):
                        outputs = model(inputs)
                        _, preds = torch.max(outputs, 1)
                        loss = criterion(outputs, labels)

                        # backward + optimize only if in training phase
                        if phase == 'train':
                            loss.backward()
                            optimizer.step()

                    # statistics
                    running_loss += loss.item() * inputs.size(0)
                    running_corrects += torch.sum(preds == labels.data)
                if phase == 'train':
                    scheduler.step()

            epoch_loss = running_loss / (chunks*2169)
            epoch_acc = running_corrects.double() / (chunks*2169)

            print('{} Loss: {:.4f} Acc: {:.4f}'.format(
                phase, epoch_loss, epoch_acc))

            # deep copy the model
            if phase == 'val' and epoch_acc > best_acc:
                best_acc = epoch_acc
                best_model_wts = copy.deepcopy(model.state_dict())

    time_elapsed = time.time() - since
    print('Training complete in {:.0f}m {:.0f}s'.format(
        time_elapsed // 60, time_elapsed % 60))
    print('Best val Acc: {:4f}'.format(best_acc))

    # load best model weights
    model.load_state_dict(best_model_wts)
    return model

In [43]:
def test_model(model, criterion):
    model.eval()
    X, Y = torch.load('data/images-9.pt'),\
           torch.load('data/labels-9.pt')
    running_loss = 0.0
    running_corrects = 0
    train = data_utils.TensorDataset(X, Y)
    
    all_outputs = []
    all_labels = []
    
    train_loader = data_utils.DataLoader(train, batch_size=64, shuffle=True)
    for inputs, labels in train_loader:
        inputs = inputs.to(device)
        labels = labels.to(device)

        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)
        loss = criterion(outputs, labels)

        # statistics
        running_loss += loss.item() * inputs.size(0)
        running_corrects += torch.sum(preds == labels.data)
        
        all_outputs.append(outputs.cpu())
        all_labels.append(labels.cpu())
            
    loss = running_loss
    acc = running_corrects.double() / (len(Y))

    print('Test Loss: {:.4f} Acc: {:.4f}'.format(
        loss, acc))
    
    all_outputs = torch.cat((*all_outputs,))
    all_labels = torch.cat((*all_labels,))
    
    return all_outputs, all_labels

In [74]:
criterion = nn.CrossEntropyLoss(weight=torch.Tensor([1,6]).to(device))
model = torch.load('models/vgg19_83.pt')
preds, labels = test_model(model, criterion)

Test Loss: 22600.3762 Acc: 0.8439


In [66]:
positive_preds = preds[:,1]
positive_preds

array([-12.109841, -17.844172, -40.22474 , ..., -56.390015, -59.2533  ,
       -28.091951], dtype=float32)

In [77]:
sm = nn.Softmax()
roc_preds = sm(preds).detach().numpy()[:,1]
roc_labels = labels.detach().numpy()
roc_preds, roc_labels

/home/paperspace/.local/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  


(array([1.0317825e-01, 0.0000000e+00, 9.6148248e-14, ..., 2.6629274e-10,
        6.2688561e-23, 6.6592953e-18], dtype=float32),
 array([0, 0, 0, ..., 0, 0, 0]))

In [78]:
def get_roc_curve(labels, preds):
    return roc_curve(labels, preds)
get_roc_curve(roc_labels, roc_preds)

(array([0.        , 0.05626598, 0.05984655, 0.06138107, 0.0629156 ,
        0.06445013, 0.06547315, 0.06803069, 0.06905371, 0.07109974,
        0.07109974, 0.07263427, 0.07263427, 0.07365729, 0.07365729,
        0.07468031, 0.07468031, 0.07519182, 0.07519182, 0.07672634,
        0.07672634, 0.07723785, 0.07723785, 0.08286445, 0.08286445,
        0.08337596, 0.08337596, 0.08797954, 0.08797954, 0.09002558,
        0.09002558, 0.09258312, 0.09258312, 0.09514066, 0.09514066,
        0.0971867 , 0.0971867 , 0.09769821, 0.09769821, 0.09974425,
        0.09974425, 0.10025575, 0.10025575, 0.10076726, 0.10076726,
        0.10332481, 0.10332481, 0.10485934, 0.10485934, 0.10588235,
        0.10588235, 0.11508951, 0.11508951, 0.11764706, 0.11764706,
        0.11815857, 0.11815857, 0.12071611, 0.12071611, 0.12429668,
        0.12429668, 0.12531969, 0.12531969, 0.12890026, 0.12890026,
        0.13043478, 0.13043478, 0.13401535, 0.13401535, 0.13554987,
        0.13554987, 0.1370844 , 0.1370844 , 0.13

In [16]:
a = torch.tensor([]).to(device)
b = torch.tensor([1,2,3]).to(device)

In [18]:
roc_curve

RuntimeError: Expected object of scalar type Float but got scalar type Long for sequence element 1 in sequence argument at position #1 'tensors'

TypeError: empty(): argument 'size' (position 1) must be tuple of ints, not NoneType

In [23]:
torch.empty(size=(2169,))

tensor([ 3.9236e-44,  4.5852e-41, -3.0092e+12,  ...,  5.3759e-24,
         4.5852e-41,  5.3757e-24])